#Arquivo de configuracao do pipeline Circle CI
# Versao do Circle CI
version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0
  aws-cli: circleci/aws-cli@3.1.4
  # synk: snyk/snyk@1.4.0

jobs:
  build: 
    docker:
      - image: cimg/node:22.18.0
    steps:
      - checkout
      - run: 
          name: "Instalar angular"
          command: sudo npm install -g @angular/cli
      - run: 
          name: "Instalar grunt"
          command: sudo npm install -g grunt-cli
      - run: 
          name: "Instalar dependencias"
          command: npm install
      - run: 
          name: "Listar Arquivos"
          command: ls -la
      - persist_to_workspace:
          root: .
          paths:
            - ./*
          
  test:
    docker:
      - image: cimg/node:22.18.0-browsers
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: "Adicionar repositorio do Mozilla Team"
          command: |
            sudo add-apt-repository -y ppa:mozillateam/ppa -y
            echo '
            Package: firefox*
            Pin: release o=LP-PPA-mozillateam
            Pin-Priority: 501
            ' | sudo tee /etc/apt/preferences.d/mozilla-firefox
      - run: 
          name: "Instalar Firefox"
          command: | 
            sudo apt-get update
            sudo apt-get install -y firefox
      - run: 
          name: "Verificar versao do Firefox"
          command: firefox --version
      - run: 
          name: "Instalar Google Chrome"
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      - run:
          name: "Configurar CHROME_BIN"
          command: echo 'export CHROME_BIN=/usr/bin/google-chrome' >> $BASH_ENV
      - run: 
          name: "Listar arquivos"
          command: ls -la
      - run: 
          name: "Instalar Angular CLI"
          command: sudo npm install -g @angular/cli
      - run: 
          name: "Instalar Grunt CLI"
          command: sudo npm install -g grunt-cli
      - run: 
          name: "Rodar testes"
          command: npm run test

  # Executar o Software Composition Analysis (SCA) com Snyk
  test_sca:
    docker:
      - image: cimg/node:22.18.0
    
    environment:
      APP_NAME: "Juice Shop"
      DEFECT_DOJO_API_URL: "https://defectdojo.soulsec.net/api/v2/import-scan/"
      SCAN_TYPE: "Snyk Scan"
      REPORT_FILE: "snyk-report.json"
    
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Instalar Snyk CLI"
          command: npm install -g snyk
      - run:
          name: "Rodar Snyk Test"
          command: snyk test --severity-threshold=high --json-file-output=${REPORT_FILE} || true
      - run:
          name: "Rodar Snyk Monitor"
          command: snyk monitor --project-name=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH} || true

  deploy-branch-1:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default

      # BUILD A IMAGEM DOCKER E PUBLICAR NO DOCKER HUB
      - run:  
          name: "Build e Push da imagem Docker no Docker Hub"
          command: docker build -t $DOCKERHUB_USERNAME/juice-shop:$CIRCLE_SHA1 -t $DOCKERHUB_USERNAME/juice-shop:latest ./
      - run: 
          name: "Login no Docker Hub"
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run: 
          name: "Push da imagem Docker no Docker Hub"
          command: docker push $DOCKERHUB_USERNAME/juice-shop:$CIRCLE_SHA1
      - run: 
          name: "Push da imagem Docker com a tag latest no Docker Hub"
          command: docker push $DOCKERHUB_USERNAME/juice-shop:latest

      # ATUALIZAR A APLICACAO NO AWS ELASTIC BEANSTALK
      - run:
          name: "Instalar AWS CLI"
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: "Deploy no AWS Elastic Beanstalk"
          command: |
            aws configure set region sa-east-1
            aws s3 cp ebs-app-options.json s3://juice-shop-tr-env-prod/ebs-app-options-$CIRCLE_SHA1.json
            aws elasticbeanstalk create-application-version --application-name juice-shop-app-prod --version-label $CIRCLE_SHA1 --source-bundle S3Bucket="juice-shop-tr-env-prod",S3Key="ebs-app-options-$CIRCLE_SHA1.json"
            aws elasticbeanstalk update-environment --environment-name juice-shop-env-prod --version-label $CIRCLE_SHA1


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - test_sca:
          requires:
            - build
      # - deploy-stg:
      #     requires:
      #       - test
      #       - test_sca
      #     filters:
      #       branches:
      #         only: staging
      # - deploy-prod:
      #     requires:
      #       - test
      #       - test_sca
      #     filters:
      #       branches:
      #         only: master
      - deploy-branch-1:
          requires:
            - test
            - test_sca
          filters:
            branches:
              only: branch-1